config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resources :users
  resources :customers, only: :index

  authenticate :user do
    resources :cars do
      collection do
        get :modal
      end
    end
  end

  root "home#index"
end

app/controllers/customers_controller.rb
class CustomersController < ApplicationController
  before_action :authenticate_user!

  def index
    authorize! :index, User

    @q = User.customers
    @q = @q.search(params[:q]) if params[:q].present?
    @customers = @q.deep.sorted.page(params[:page])
  end
end

app/views/customers/index.html.haml
%main{ data: { controller: "customers" }}
  .flex-col.md:flex-row.md:inline-flex.md:justify-around.md:items-center.w-full
    %h1.text-4xl.text-left.text-gray-900.mb-12.dark:text-white.font-bold
      Clientes

    .inline-flex.mb-12.ml-auto.w-full.md:w-auto.h-10
      = form_with url: customers_path, method: :get, class: 'w-full' do |f|
        = f.search_field :q, value: params[:q], placeholder: "Pesquise por carro ou cliente...", class: "h-full w-full md:w-48 lg:w-72 border-gray-300 dark:bg-gray-700 dark:border-gray-600 focus:ring-blue-500 focus:border-blue-500 dark:focus:ring-blue-600 dark:focus:border-blue-600 rounded-md shadow-sm"
        = f.submit "Pesquisar", class: "h-full mt-3 md:mt-0 w-full md:w-24 lg:w-36 md:ml-2 inline-flex justify-center py-2 px-4 border border-transparent shadow-sm text-sm font-medium rounded-md text-white bg-blue-600 hover:bg-blue-700 dark:bg-blue-500 dark:hover:bg-blue-600 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-blue-500"

  .relative.overflow-x-auto.shadow-sm
    %table.w-full.text-sm.text-left.text-gray-500.dark:text-gray-400
      %thead.text-xs.text-gray-700.uppercase.bg-gray-50.dark:bg-gray-700.dark:text-gray-400
        %tr
          -# %th.p-4{scope: "col"}
          -#   .flex.items-center
          -#     %input#checkbox-all-search.w-4.h-4.text-blue-600.bg-gray-100.border-gray-300.rounded.focus:ring-blue-500.dark:focus:ring-blue-600.dark:ring-offset-gray-800.dark:focus:ring-offset-gray-800.focus:ring-2.dark:bg-gray-700.dark:border-gray-600{type: "checkbox"}/
          -#     %label.sr-only{for: "checkbox-all-search"} checkbox
          %th.px-6.py-3{scope: "col"}
            Cliente
          %th.px-6.py-3{scope: "col"}
            E-mail
          %th.px-6.py-3{scope: "col"}
            Carros
          %th.px-6.py-3{scope: "col"}
            Ações
      %tbody
        - @customers.each do |customer|
          %tr.bg-white.border-b.dark:bg-gray-800.dark:border-gray-700.hover:bg-gray-50.dark:hover:bg-gray-600
            -# %td.w-4.p-4
            -#   .flex.items-center
            -#     %input#checkbox-table-search-1.w-4.h-4.text-blue-600.bg-gray-100.border-gray-300.rounded.focus:ring-blue-500.dark:focus:ring-blue-600.dark:ring-offset-gray-800.dark:focus:ring-offset-gray-800.focus:ring-2.dark:bg-gray-700.dark:border-gray-600{type: "checkbox"}/
            -#     %label.sr-only{for: "checkbox-table-search-1"} checkbox
            %th.px-6.py-4.font-medium.text-gray-900.whitespace-nowrap.dark:text-white{scope: "row"}
              = customer
            %td.px-6.py-4
              = customer.email
            %td.px-6.py-4
              - customer.cars.each do |car|
                = link_to car, car_path(car), class: "font-bold hover:text-blue-400"
                %br
            %td.px-6.py-4.inline-flex.items-center
              = link_to cars_path(user_id: customer), class: "font-medium text-gray-600 hover:text-blue-500 dark:text-gray-500" do
                = icon 'eye'
              = link_to edit_user_path(customer), class: "font-medium text-gray-600 hover:text-blue-500 dark:text-gray-500 ml-3" do
                = icon 'pencil'
              = link_to masquerade_path(customer), class: "font-medium text-gray-600 hover:text-blue-500 dark:text-gray-500 ml-3" do
                = icon 'play'
              = link_to customer, method: :delete, data: { confirm: "Deseja realmente excluir #{customer}?" }, class: "font-medium text-red-600 hover:text-red-400 dark:text-red-500 ml-3" do
                = icon 'trash'

    = paginate @customers