config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resources :users
  resources :customers, only: :index

  authenticate :user do
    resources :cars do
      collection do
        get :modal
      end
    end
  end

  root "home#index"
end

app/models/car.rb
class Car < ApplicationRecord
  self.inheritance_column = nil

  belongs_to :user

  has_many :services, class_name: "Services::Service", dependent: :destroy

  before_validation :upcase_plate

  validates :brand, :model, :year_model, :mileage, :plate, :color, presence: true
  validates :year_make,  inclusion: { in: 1900..Date.today.year }
  validates :year_model, inclusion: { in: 1900..Date.today.year }
  validates :plate, uniqueness: true, format: { with: /\A[A-Z]{3}-\d[A-Z0-9]\d{2}\z/i }
  validates :mileage, numericality: { greater_than_or_equal_to: 0 }

  with_options(if: -> { !new_record? }) do
    validates :mileage, numericality: { greater_than_or_equal_to: :mileage_was }
  end

  def to_s
    "#{brand} #{model} #{year_model}"
  end

  private

  def upcase_plate
    self.plate = plate.to_s.upcase
  end
end

# == Schema Information
#
# Table name: cars
#
#  id         :bigint           not null, primary key
#  brand      :string           not null
#  color      :string           not null
#  mileage    :integer          not null
#  model      :string           not null
#  plate      :string           not null
#  type       :string
#  version    :string
#  year_make  :integer
#  year_model :integer
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  user_id    :integer          not null
#
# Indexes
#
#  index_cars_on_user_id  (user_id)
#

app/controllers/cars_controller.rb
class CarsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_car, only: %i[ show edit update destroy ]

  # GET /cars
  def index
    authorize! :index, Car

    @cars = Car.includes(:services)
    @cars = @cars.where(user: filtered_user)
    @cars = @cars.order(brand: :asc, model: :asc, year_model: :asc)
  end

  # GET /cars/1
  def show
    authorize! :read, @car

    redirect_to edit_car_path(@car)
  end

  # GET /cars/new
  def new
    authorize! :create, Car

    @car = Car.new
  end

  # GET /cars/1/edit
  def edit
    authorize! :update, @car
  end

  # POST /cars
  def create
    authorize! :create, Car

    @car = Car.new(car_params)

    if @car.save
      redirect_to @car, notice: "Car was successfully created."
    else
      render :new, status: :unprocessable_entity
    end
  end

  # PATCH/PUT /cars/1
  def update
    authorize! :update, @car

    if @car.update(car_params)
      redirect_to @car, notice: "Car was successfully updated.", status: :see_other
    else
      render :edit, status: :unprocessable_entity
    end
  end

  # DELETE /cars/1
  def destroy
    authorize! :destroy, @car

    @car.destroy
    redirect_to cars_url, notice: "Car was successfully destroyed.", status: :see_other
  end

  def modal
    authorize! :index, Car

    @service = Services::Service.find(params[:service_id])
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_car
      @car = Car.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def car_params
      params.require(:car).permit(:brand, :model, :version, :type, :plate, :mileage, :year_make, :year_model, :color, :user_id)
    end
end

app/helpers/cars_helper.rb
module CarsHelper
end

app/views/cars/_car.html.haml
%div{id: "#{dom_id car}"}
  %p.my-5
    %strong.block.font-medium.mb-1:
    = car.brand
  %p.my-5
    %strong.block.font-medium.mb-1:
    = car.model
  %p.my-5
    %strong.block.font-medium.mb-1:
    = car.version
  %p.my-5
    %strong.block.font-medium.mb-1:
    = car.type
  %p.my-5
    %strong.block.font-medium.mb-1:
    = car.plate
  %p.my-5
    %strong.block.font-medium.mb-1:
    = car.mileage
  %p.my-5
    %strong.block.font-medium.mb-1:
    = car.year_make
  %p.my-5
    %strong.block.font-medium.mb-1:
    = car.year_model
  %p.my-5
    %strong.block.font-medium.mb-1:
    = car.color
  - if action_name != "show"
    = link_to "Detalhes", car, class: "rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium"
    = link_to 'Editar', edit_car_path(car), class: "rounded-lg py-3 ml-2 px-5 bg-gray-100 inline-block font-medium"
    %hr.mt-6/

app/views/cars/_form.html.haml
= form_with(model: car, class: "contents") do |form|
  - if car.errors.any?
    #error_explanation.bg-red-50.text-red-500.px-3.py-2.font-medium.rounded-lg.mt-3
      %h2
        = car.errors.count
        erro(s) ao registrar:
      %ul
        - car.errors.each do |error|
          %li= error.full_message

  .w-full.mt-10
    = form.label :user_id
    = form.select :user_id, User.customers.sorted.map { |user| [user, user.id] }, { include_blank: "Selecione um usuário" }, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full"

  .w-full.inline-flex.justify-between.mt-3
    .w-full.mr-2
      = form.label :brand
      = form.text_field :brand, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full"
    .w-full.mr-2
      = form.label :model
      = form.text_field :model, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full"
    .w-full
      = form.label :version
      = form.text_field :version, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full"

  .w-full.mt-3
    = form.label :type
    = form.text_field :type, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full"
  .w-full.mt-3
    = form.label :plate
    = form.text_field :plate, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full"
  .w-full.mt-3
    = form.label :mileage
    = form.number_field :mileage, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full"

  .w-full.inline-flex.justify-between.mt-3
    .w-full.mr-2
      = form.label :year_make
      = form.number_field :year_make, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full"
    .w-full
      = form.label :year_model
      = form.number_field :year_model, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full"

  .w-full.mt-3
    = form.label :color
    = form.text_field :color, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full"

  .inline-flex.mt-10
    = form.submit "Salvar", class: "rounded-lg py-3 px-5 bg-blue-600 text-white inline-block font-medium cursor-pointer"

app/views/cars/_service.html.haml
.lg:max-w-lg.rounded.overflow-hidden.shadow-sm.w-full.mb-8.cursor-pointer.shadow-lg.hover:shadow-xl.dark:bg-gray-800.dark:text-gray-100.shadow-gray-400.dark:shadow-none.dark:hover:bg-gray-700
  .px-6.py-4
    .font-bold.text-xl.mb-2.text-gray-600.dark:text-gray-200= service.name
    %p.text-gray-700.text-base.dark:text-gray-400= service.description
  .px-6.pt-4.pb-2.flex.items-center.justify-between.align-middle
    %div
      = service_status_icon service.status

    %div.text-sm.text-gray-500.hover:text-blue-500
      Ver Detalhes &rarr;

app/views/cars/edit.html.haml
- if can? :edit, @car
  .mx-auto.w-full{class: "md:w-2/3"}
    %h1.font-bold.text-4xl Editar #{@car}
    = render "form", car: @car
    = link_to "Voltar", cars_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium"

app/views/cars/index.html.haml
%main{ data: { controller: "cars" }}
  .flex.flex-row.justify-between.mx-0.lg:mx-20
    %div
      %h1.text-3xl.text-center.lg:text-left.text-gray-900.mb-12.dark:text-white.font-bold
        Meus Carros

      .text-center
        - unless @cars.exists?
          %p.text-gray-600
            Não há nenhum carro cadastrado para você por enquanto.

      .mx-auto
        .flex.flex-col.justify-between.w-full
          - @cars.each_with_index do |car, index|
            %h3.inline-flex.text-2xl.text-gray-700.dark:text-white.mb-8{ class: index > 0 && "mt-4" }
              = link_to car_path(car) do
                .inline-flex.items-center.text-gray-700.hover:underline.dark:text-white
                  = icon 'wrench-screwdriver'
                  .ml-2= car

              - if can?(:create, Car)
                .ml-auto.inline-flex.items-center
                  = icon 'plus', '', class: "bg-gray-100 text-gray-400 hover:bg-gray-200 font-bold cursor-pointer h-6 w-6 rounded-full"

            %hr.w-full.mb-8.dark:border-gray-400

            - if car.services.exists?
              - car.services.each do |service|
                = link_to modal_cars_path(service_id: service.id), class: "flex w-full text-left", data: { turbo_frame: 'modal' } do
                  = render "service", service: service
            - else
              %p.text-gray-600 Quando algum serviço for cadastrado para o <strong>#{car}</strong> ele aparecerá aqui.

            - if can?(:create, Service)
              .m-auto.inline-flex.items-center
                = icon 'plus', '', class: "bg-gray-100 text-gray-400 hover:bg-gray-200 font-bold cursor-pointer h-9 w-9 rounded-full"

    .h-full.max-w-md.items-center.my-auto.ml-20.hidden.lg:flex
      = image_tag 'ai-002.png'

= turbo_frame_tag "modal"

app/views/cars/modal.html.haml
= turbo_frame_tag "modal" do
  %div{ data: { controller: "cars--modal" }}
    #backdrop.bg-black.opacity-30.w-full.h-full.fixed.top-0.bottom-0.left-0.right-0
    .fixed.left-0.right-0.z-50.w-full.p-4.overflow-x-hidden.overflow-y-auto.md:inset-0.max-h-full{tabindex: "-1", class: "top-36 lg:top-60"}
      .relative.w-full.max-w-3xl.max-h-full.m-auto.drop-shadow-md
        / Modal content
        .relative.bg-white.rounded-lg.shadow.dark:bg-white
          / Modal header
          .flex.items-start.justify-between.p-4.border-b.rounded-t.dark:border-gray-400
            %h3.text-xl.font-semibold.text-gray-600.dark:text-gray-900
              Descrição do Serviço
            = button_tag "", type: "button", class: "text-gray-400 bg-transparent hover:bg-gray-200 dark:hover:bg-gray-200 hover:text-gray-900 rounded-lg text-sm w-8 h-8 ml-auto inline-flex justify-center items-center dark:hover:bg-gray-600 dark:hover:text-whitedata", data: { action: "cars--modal#hideModal" } do
              %svg.w-3.h-3{"aria-hidden" => "true", fill: "none", viewbox: "0 0 14 14", xmlns: "http://www.w3.org/2000/svg"}
                %path{d: "m1 1 6 6m0 0 6 6M7 7l6-6M7 7l-6 6", stroke: "currentColor", "stroke-linecap" => "round", "stroke-linejoin" => "round", "stroke-width" => "2"}
              %span.sr-only Fechar
          / Modal body
          .p-6.space-y-6
            %p.text-base.leading-relaxed.text-gray-500.dark:text-gray-900
              = @service.description

            - if @service.steps.exists?
              .flex.flex-col.lg:flex-row.h-full
                %ol
                  - @service.steps.sorted.each do |step|
                    %li.mb-3
                      .px-6.py-4
                        .font-bold.text-xl.mb-2.text-gray-600.dark:text-gray-200
                          = step.name
                        .text-gray-700.text-base.dark:text-gray-400{ class: "w-5/6 md:w-2/3" }
                          = step.description
                      .px-6.pb-2.flex.items-center.justify-between.align-middle
                        %div
                          = service_step_status_icon step.status

                      %hr.my-2.ml-5.border-dashed.border-gray-400{ class: "w-5/6 md:w-2/3" }

                .mt-24.mx-auto
                  = image_tag 'car-repair.svg'

app/views/cars/new.html.haml
.mx-auto.w-full{class: "md:w-2/3"}
  %h1.font-bold.text-4xl
    Novo Carro
  = render "form", car: @car
  = link_to 'Voltar', cars_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium"

app/views/cars/show.html.haml
.mx-auto.w-full.flex{class: "md:w-2/3"}
  .mx-auto
    - if notice.present?
      %p#notice.py-2.px-3.bg-green-50.mb-5.text-green-500.font-medium.rounded-lg.inline-block= notice
    = render @car
    = link_to 'Editar', edit_car_path(@car), class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium"
    .inline-block.ml-2
      = button_to 'Excluir', car_path(@car), method: :delete, class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 font-medium"
    = link_to 'Voltar', cars_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium"